CC       =g++
CFLAGS	=-Wall -g  -o
COMMON  =
INCLUDE	=
LINK	=m


phone.out: phone.cpp $(COMMON)
	$(CC) $(CFLAGS) $@ $< $(COMMON) -l$(LINK) 
count.out: count.cpp $(COMMON)
	$(CC) $(CFLAGS) $@ $< $(COMMON) -l$(LINK) 
divisor.out: divisor.cpp $(COMMON)
	$(CC) $(CFLAGS) $@ $< $(COMMON) -l$(LINK) 
expr.out: expr.cpp $(COMMON)
	$(CC) $(CFLAGS) $@ $< $(COMMON) -l$(LINK) 
add.out: add.cpp $(COMMON)
	$(CC) $(CFLAGS) $@ $< $(COMMON) -l$(LINK) 

#-I$(INCLUDE)
